"""Add public site columns to inventory

Revision ID: 0595a536d00c
Revises: h1i2j3k4l5m6
Create Date: 2026-02-08 00:48:15.808156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0595a536d00c'
down_revision = 'h1i2j3k4l5m6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('retail_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('short_verdict', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pros', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('cons', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('specs', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('pick_category', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_inventory_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_pick_category'), ['pick_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_slug'))
        batch_op.drop_index(batch_op.f('ix_inventory_pick_category'))
        batch_op.drop_index(batch_op.f('ix_inventory_is_published'))
        batch_op.drop_column('pick_category')
        batch_op.drop_column('specs')
        batch_op.drop_column('is_published')
        batch_op.drop_column('slug')
        batch_op.drop_column('rating')
        batch_op.drop_column('cons')
        batch_op.drop_column('pros')
        batch_op.drop_column('short_verdict')
        batch_op.drop_column('retail_price')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
