"""Add password reset fields to User

Revision ID: 5921251cfedc
Revises: f744066e33f4
Create Date: 2026-01-16 15:48:12.281946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5921251cfedc'
down_revision = 'f744066e33f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_reset_expires', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_password_reset_token'), ['password_reset_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_password_reset_token'))
        batch_op.drop_column('password_reset_expires')
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###
